server:
  port: 8080
  
spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/circle_of_friends?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

#showSql
logging:
  level:
    com:
      example:
        mapper: debug