server:
  port: 8081
  
spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/tiantian_canteen?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

#showSql
logging:
  level:
    com:
      example:
        mapper: debug
        
#DEFAULT
default:
  # 文件上传目录
  uploadPath: C:/Users/ZhengBoShao/Desktop/fileUpload/
  # 默认图片
  img: http://img.zcool.cn/community/01a92a5a151826a80120518742bb1d.JPG
        
# Swagger界面内容配置
swagger:
  title: API接口文档
  description: TMax Api Documentation
  version: 1.0.0
  termsOfServiceUrl: https://github.com/vue-springboot-money/bysj_vue_springboot
  contact:
    name: shaozhenngbo
    url: https://github.com/vue-springboot-money/bysj_vue_springboot
    email: shaoISzhengbo@163.com